//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LT.WCF.DesktopClient.WcfServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderAndOrderItemsAndProducts", Namespace="http://schemas.datacontract.org/2004/07/LT.WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class OrderAndOrderItemsAndProducts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrdreDatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdreIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdreStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProduktAntalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProduktBeskrivelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProduktNavnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrdreDato {
            get {
                return this.OrdreDatoField;
            }
            set {
                if ((this.OrdreDatoField.Equals(value) != true)) {
                    this.OrdreDatoField = value;
                    this.RaisePropertyChanged("OrdreDato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrdreId {
            get {
                return this.OrdreIdField;
            }
            set {
                if ((this.OrdreIdField.Equals(value) != true)) {
                    this.OrdreIdField = value;
                    this.RaisePropertyChanged("OrdreId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdreStatus {
            get {
                return this.OrdreStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdreStatusField, value) != true)) {
                    this.OrdreStatusField = value;
                    this.RaisePropertyChanged("OrdreStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProduktAntal {
            get {
                return this.ProduktAntalField;
            }
            set {
                if ((this.ProduktAntalField.Equals(value) != true)) {
                    this.ProduktAntalField = value;
                    this.RaisePropertyChanged("ProduktAntal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProduktBeskrivelse {
            get {
                return this.ProduktBeskrivelseField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduktBeskrivelseField, value) != true)) {
                    this.ProduktBeskrivelseField = value;
                    this.RaisePropertyChanged("ProduktBeskrivelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProduktNavn {
            get {
                return this.ProduktNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduktNavnField, value) != true)) {
                    this.ProduktNavnField = value;
                    this.RaisePropertyChanged("ProduktNavn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/LT.WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceReference.IWcfService")]
    public interface IWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetOrders", ReplyAction="http://tempuri.org/IWcfService/GetOrdersResponse")]
        LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetOrders", ReplyAction="http://tempuri.org/IWcfService/GetOrdersResponse")]
        System.Threading.Tasks.Task<LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[]> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetOrdersById", ReplyAction="http://tempuri.org/IWcfService/GetOrdersByIdResponse")]
        LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[] GetOrdersById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetOrdersById", ReplyAction="http://tempuri.org/IWcfService/GetOrdersByIdResponse")]
        System.Threading.Tasks.Task<LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[]> GetOrdersByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetProducts", ReplyAction="http://tempuri.org/IWcfService/GetProductsResponse")]
        LT.WCF.DesktopClient.WcfServiceReference.Product[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetProducts", ReplyAction="http://tempuri.org/IWcfService/GetProductsResponse")]
        System.Threading.Tasks.Task<LT.WCF.DesktopClient.WcfServiceReference.Product[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetProductById", ReplyAction="http://tempuri.org/IWcfService/GetProductByIdResponse")]
        LT.WCF.DesktopClient.WcfServiceReference.Product GetProductById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetProductById", ReplyAction="http://tempuri.org/IWcfService/GetProductByIdResponse")]
        System.Threading.Tasks.Task<LT.WCF.DesktopClient.WcfServiceReference.Product> GetProductByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/CreateProduct", ReplyAction="http://tempuri.org/IWcfService/CreateProductResponse")]
        void CreateProduct(string name, string description, double price, int stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/CreateProduct", ReplyAction="http://tempuri.org/IWcfService/CreateProductResponse")]
        System.Threading.Tasks.Task CreateProductAsync(string name, string description, double price, int stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/UpdateProduct", ReplyAction="http://tempuri.org/IWcfService/UpdateProductResponse")]
        void UpdateProduct(int id, string name, string description, double price, int stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/UpdateProduct", ReplyAction="http://tempuri.org/IWcfService/UpdateProductResponse")]
        System.Threading.Tasks.Task UpdateProductAsync(int id, string name, string description, double price, int stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/DeleteProduct", ReplyAction="http://tempuri.org/IWcfService/DeleteProductResponse")]
        void DeleteProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/DeleteProduct", ReplyAction="http://tempuri.org/IWcfService/DeleteProductResponse")]
        System.Threading.Tasks.Task DeleteProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/CloseOrder", ReplyAction="http://tempuri.org/IWcfService/CloseOrderResponse")]
        void CloseOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/CloseOrder", ReplyAction="http://tempuri.org/IWcfService/CloseOrderResponse")]
        System.Threading.Tasks.Task CloseOrderAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceChannel : LT.WCF.DesktopClient.WcfServiceReference.IWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceClient : System.ServiceModel.ClientBase<LT.WCF.DesktopClient.WcfServiceReference.IWcfService>, LT.WCF.DesktopClient.WcfServiceReference.IWcfService {
        
        public WcfServiceClient() {
        }
        
        public WcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[] GetOrdersById(string id) {
            return base.Channel.GetOrdersById(id);
        }
        
        public System.Threading.Tasks.Task<LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[]> GetOrdersByIdAsync(string id) {
            return base.Channel.GetOrdersByIdAsync(id);
        }
        
        public LT.WCF.DesktopClient.WcfServiceReference.Product[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<LT.WCF.DesktopClient.WcfServiceReference.Product[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public LT.WCF.DesktopClient.WcfServiceReference.Product GetProductById(int id) {
            return base.Channel.GetProductById(id);
        }
        
        public System.Threading.Tasks.Task<LT.WCF.DesktopClient.WcfServiceReference.Product> GetProductByIdAsync(int id) {
            return base.Channel.GetProductByIdAsync(id);
        }
        
        public void CreateProduct(string name, string description, double price, int stock) {
            base.Channel.CreateProduct(name, description, price, stock);
        }
        
        public System.Threading.Tasks.Task CreateProductAsync(string name, string description, double price, int stock) {
            return base.Channel.CreateProductAsync(name, description, price, stock);
        }
        
        public void UpdateProduct(int id, string name, string description, double price, int stock) {
            base.Channel.UpdateProduct(id, name, description, price, stock);
        }
        
        public System.Threading.Tasks.Task UpdateProductAsync(int id, string name, string description, double price, int stock) {
            return base.Channel.UpdateProductAsync(id, name, description, price, stock);
        }
        
        public void DeleteProduct(int id) {
            base.Channel.DeleteProduct(id);
        }
        
        public System.Threading.Tasks.Task DeleteProductAsync(int id) {
            return base.Channel.DeleteProductAsync(id);
        }
        
        public void CloseOrder(int id) {
            base.Channel.CloseOrder(id);
        }
        
        public System.Threading.Tasks.Task CloseOrderAsync(int id) {
            return base.Channel.CloseOrderAsync(id);
        }
    }
}
