//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LT.WCF.DesktopClient.WcfServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderAndOrderItemsAndProducts", Namespace="http://schemas.datacontract.org/2004/07/LT.WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class OrderAndOrderItemsAndProducts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrdreDatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdreIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdreStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProduktAntalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProduktBeskrivelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProduktNavnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrdreDato {
            get {
                return this.OrdreDatoField;
            }
            set {
                if ((this.OrdreDatoField.Equals(value) != true)) {
                    this.OrdreDatoField = value;
                    this.RaisePropertyChanged("OrdreDato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrdreId {
            get {
                return this.OrdreIdField;
            }
            set {
                if ((this.OrdreIdField.Equals(value) != true)) {
                    this.OrdreIdField = value;
                    this.RaisePropertyChanged("OrdreId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdreStatus {
            get {
                return this.OrdreStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdreStatusField, value) != true)) {
                    this.OrdreStatusField = value;
                    this.RaisePropertyChanged("OrdreStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProduktAntal {
            get {
                return this.ProduktAntalField;
            }
            set {
                if ((this.ProduktAntalField.Equals(value) != true)) {
                    this.ProduktAntalField = value;
                    this.RaisePropertyChanged("ProduktAntal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProduktBeskrivelse {
            get {
                return this.ProduktBeskrivelseField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduktBeskrivelseField, value) != true)) {
                    this.ProduktBeskrivelseField = value;
                    this.RaisePropertyChanged("ProduktBeskrivelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProduktNavn {
            get {
                return this.ProduktNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduktNavnField, value) != true)) {
                    this.ProduktNavnField = value;
                    this.RaisePropertyChanged("ProduktNavn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceReference.IWcfService")]
    public interface IWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetOrders", ReplyAction="http://tempuri.org/IWcfService/GetOrdersResponse")]
        LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetOrders", ReplyAction="http://tempuri.org/IWcfService/GetOrdersResponse")]
        System.Threading.Tasks.Task<LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[]> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetOrdersById", ReplyAction="http://tempuri.org/IWcfService/GetOrdersByIdResponse")]
        LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[] GetOrdersById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetOrdersById", ReplyAction="http://tempuri.org/IWcfService/GetOrdersByIdResponse")]
        System.Threading.Tasks.Task<LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[]> GetOrdersByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/CloseOrder", ReplyAction="http://tempuri.org/IWcfService/CloseOrderResponse")]
        void CloseOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/CloseOrder", ReplyAction="http://tempuri.org/IWcfService/CloseOrderResponse")]
        System.Threading.Tasks.Task CloseOrderAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceChannel : LT.WCF.DesktopClient.WcfServiceReference.IWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceClient : System.ServiceModel.ClientBase<LT.WCF.DesktopClient.WcfServiceReference.IWcfService>, LT.WCF.DesktopClient.WcfServiceReference.IWcfService {
        
        public WcfServiceClient() {
        }
        
        public WcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[] GetOrdersById(string id) {
            return base.Channel.GetOrdersById(id);
        }
        
        public System.Threading.Tasks.Task<LT.WCF.DesktopClient.WcfServiceReference.OrderAndOrderItemsAndProducts[]> GetOrdersByIdAsync(string id) {
            return base.Channel.GetOrdersByIdAsync(id);
        }
        
        public void CloseOrder(int id) {
            base.Channel.CloseOrder(id);
        }
        
        public System.Threading.Tasks.Task CloseOrderAsync(int id) {
            return base.Channel.CloseOrderAsync(id);
        }
    }
}
